import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import React from "react";
import { GiDeerTrack, GiClick } from "react-icons/gi";
import { getFileNum } from "@/redux/features/alphaSlice";
import { useSelector, useDispatch } from "react-redux";
import { MdOutlineAssignmentTurnedIn, MdPreview } from "react-icons/md";
import { GrAchievement } from "react-icons/gr";
import { FcApproval } from "react-icons/fc";
import Navv from "@/components/Navv";
import { useRouter } from "next/router";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  let dispatch = useDispatch();
  const [formData, setFormData] = React.useState({
    first: "",
    second: "",
    third: "",
    fourth: "",
    fifth: "",
  });

  let router = useRouter();

  React.useEffect(() => {
    if (localStorage.getItem("profile")) {
      router.push('/files')
    }
  }, []);

  const { loading, error, filesTrack, fileById } = useSelector((stateData) => ({
    ...stateData.alpha,
  }));

   const onChange = (e) => {
     setFormData({ ...formData, [e.target.name]: e.target.value });
   };

   function onSubmit(e) {
     e.preventDefault();
     // console.log(formData);
     if (first && second && third && fourth && fifth) {
       console.log(`
         first: ${first}
         second: ${second}
         third: ${third}
         fourth: ${fourth}
         fifth: ${fifth}
       `);
       let fileNumk = first + second + third + fourth + fifth 
      //  console.log(fileNumk);
        dispatch(getFileNum(fileNumk));
     } else {
      //  toast.error("Fill up any empty space");
       console.log("Fill up any empty space");
     }
   }
  
  
  const { first, second, third, fourth, fifth } = formData;

  return (
    <>
      <Head>
        <title>Slcd web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navv/>

      <React.Fragment>
        <div className="container">
          <div className="row justify-content-center mt-7">
            <div className="col-lg-5 text-center">
              <div className="card mt-5">
                <div className="card-body py-5 px-lg-2">
                  <div className="svg-icon svg-icon-xl text-purple">
                    <GiDeerTrack className="fs-1" />
                  </div>
                  <h3 className="fw-normal text-dark mt-4">
                    Track File Progress
                  </h3>
                  <p>Please enter file number in the field below.</p>
                  <form
                    onSubmit={onSubmit}
                    className="row row-cols-2 row-cols-lg-5 g-2 g-lg-3"
                  >
                    <div className="col">
                      <input
                        type="text"
                        className="form-control text-center py-2"
                        maxLength="1"
                        autoFocus
                        name="first"
                        onChange={onChange}
                        value={first}
                      />
                    </div>
                    <div className="col">
                      <input
                        type="text"
                        className="form-control text-center py-2"
                        maxLength="1"
                        autoFocus
                        name="second"
                        onChange={onChange}
                        value={second}
                      />
                    </div>
                    <div className="col">
                      <input
                        type="text"
                        className="form-control text-center py-2"
                        maxLength="1"
                        autoFocus
                        name="third"
                        onChange={onChange}
                        value={third}
                      />
                    </div>
                    <div className="col">
                      <input
                        type="text"
                        className="form-control text-center py-2"
                        maxLength="1"
                        autoFocus
                        name="fourth"
                        onChange={onChange}
                        value={fourth}
                      />
                    </div>
                    <div className="col">
                      <input
                        type="text"
                        className="form-control text-center py-2"
                        maxLength="1"
                        autoFocus
                        name="fifth"
                        onChange={onChange}
                        value={fifth}
                      />
                    </div>

                    <button
                      type="submit"
                      className="btn btn-lg w-100 hover-lift-light mt-4 text-white"
                      style={{ background: "#6672e8", borderColor: "#6672e8" }}
                    >
                      Track Now <GiClick />
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>

          <React.Fragment>
            {loading && (
              <div className="spinner-border" role="status">
                <span className="visually-hidden">Loading...</span>
              </div>
            )}
            {!loading && error?.length > 0 ? (
              <div className="my-5">
                <h3 className="text-danger text-center">{error}</h3>
              </div>
            ) : (
              <>
                {!loading && fileById && (
                  <div className="container px-1 px-md-4 py-5 mx-auto">
                    <div className="card" style={{ zIndex: "0" }}>
                      <div className="d-flex justify-content-between">
                        <small>
                          Filed ID
                          <span className="text-primary mx-2 fw-bold">
                            {fileById?.file_name}{" "}
                          </span>
                        </small>
                        <small>
                          Created{" "}
                          <span className="fw-bold mx-2">
                            {" "}
                            {fileById?.file_date_added}{" "}
                          </span>
                        </small>
                      </div>

                      {/* <!-- Add class "active" to progress --> */}
                      <div className="row d-flex justify-content-center">
                        <div className="col-12">
                          <ul className="text-center progressbar">
                            {fileById?.agent ? (
                              <li className="active step0"></li>
                            ) : (
                              <li className="step0"></li>
                            )}
                            {filesTrack?.underReview === true ? (
                              <li className="active step0"></li>
                            ) : (
                              <li className="step0"></li>
                            )}
                            {filesTrack?.review === true ? (
                              <li className="active step0"></li>
                            ) : (
                              <li className="step0"></li>
                            )}
                            <li className="step0"></li>
                          </ul>
                        </div>
                      </div>

                      <div className="row d-flex justify-content-between mx-5 px-4 pt-5">
                        <div className="col d-flex d-flex">
                          <MdOutlineAssignmentTurnedIn className="fs-1 mx-1" />
                          <p className="font-weight-bold">
                            File <br />
                            Assigned
                          </p>
                        </div>
                        <div className="col d-flex d-flex">
                          <MdPreview className="fs-1 mx-1" />
                          <p className="font-weight-bold">
                            File Under <br />
                            Review
                          </p>
                        </div>

                        <div className="col d-flex d-flex">
                          <GrAchievement className="fs-1 mx-1" />
                          <p className="font-weight-bold">
                            File <br />
                            Reviewed
                          </p>
                        </div>

                        <div className="col d-flex d-flex">
                          <FcApproval className="fs-1 mx-1" />
                          <p className="font-weight-bold">
                            File <br />
                            Approved
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </>
            )}
          </React.Fragment>
          
        </div>
      </React.Fragment>
    </>
  );
}
